from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QMenuBar, QMenu, QFileDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 719)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.menu = QtWidgets.QTabWidget(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(0, 0, 1000, 700))
        self.menu.setObjectName("menu")

        def create_ecxel_fail(self):
            self.ecxel_fail = QtWidgets.QWidget()
            self.ecxel_fail.setObjectName("ecxel_fail")
            self.label_ex = QtWidgets.QLabel(self.ecxel_fail)
            self.label_ex.setGeometry(QtCore.QRect(330, 30, 401, 81))
            font = QtGui.QFont()
            font.setPointSize(10)
            font.setBold(True)
            font.setWeight(75)
            self.label_ex.setFont(font)
            self.label_ex.setStyleSheet("background-color: rgb(85, 255, 255);")
            self.label_ex.setObjectName("label_ex")
            self.text_ex = QtWidgets.QTextEdit(self.ecxel_fail)
            self.text_ex.setGeometry(QtCore.QRect(250, 130, 541, 51))
            self.text_ex.setObjectName("text_ex")
            self.btn_ex = QtWidgets.QPushButton(self.ecxel_fail)
            self.btn_ex.setGeometry(QtCore.QRect(390, 220, 271, 71))
            font = QtGui.QFont()
            font.setPointSize(9)
            font.setBold(True)
            font.setWeight(75)
            self.btn_ex.setFont(font)
            self.btn_ex.setStyleSheet("background-color: rgb(85, 170, 255);")
            self.btn_ex.setObjectName("btn_ex")
        create_ecxel_fail(self)
        self.menu.addTab(self.ecxel_fail, "")


        def create_graphics(self):
            self.graphics = QtWidgets.QWidget()
            self.graphics.setObjectName("graphics")
            self.menu_graphics = QtWidgets.QTabWidget(self.graphics)
            self.menu_graphics.setGeometry(QtCore.QRect(0, 0, 1000, 700))
            self.menu_graphics.setObjectName("menu_graphics")
            self.graphics_main = QtWidgets.QWidget()
            self.graphics_main.setObjectName("graphics_main")
            self.label_graph_high_1 = QtWidgets.QLabel(self.graphics_main)
            self.label_graph_high_1.setGeometry(QtCore.QRect(350, 10, 291, 21))
            font = QtGui.QFont()
            font.setPointSize(10)
            font.setBold(True)
            font.setWeight(75)
            self.label_graph_high_1.setFont(font)
            self.label_graph_high_1.setObjectName("label_graph_high_1")
            self.label_graphics_high_3 = QtWidgets.QLabel(self.graphics_main)
            self.label_graphics_high_3.setGeometry(QtCore.QRect(340, 130, 301, 21))
            font = QtGui.QFont()
            font.setPointSize(10)
            font.setBold(True)
            font.setWeight(75)
            self.label_graphics_high_3.setFont(font)
            self.label_graphics_high_3.setObjectName("label_graphics_high_3")
            self.label_graph_X_1 = QtWidgets.QLabel(self.graphics_main)
            self.label_graph_X_1.setGeometry(QtCore.QRect(630, 170, 71, 21))
            font = QtGui.QFont()
            font.setPointSize(15)
            font.setBold(True)
            font.setWeight(75)
            self.label_graph_X_1.setFont(font)
            self.label_graph_X_1.setObjectName("label_graph_X_1")
            self.label_graphics_Y_1 = QtWidgets.QLabel(self.graphics_main)
            self.label_graphics_Y_1.setGeometry(QtCore.QRect(630, 220, 71, 41))
            font = QtGui.QFont()
            font.setPointSize(15)
            font.setBold(True)
            font.setWeight(75)
            self.label_graphics_Y_1.setFont(font)
            self.label_graphics_Y_1.setObjectName("label_graphics_Y_1")
            self.label_label_high_5 = QtWidgets.QLabel(self.graphics_main)
            self.label_label_high_5.setGeometry(QtCore.QRect(240, 410, 551, 41))
            font = QtGui.QFont()
            font.setPointSize(13)
            self.label_label_high_5.setFont(font)
            self.label_label_high_5.setObjectName("label_label_high_5")
            self.formula_graph_1 = QtWidgets.QLabel(self.graphics_main)
            self.formula_graph_1.setGeometry(QtCore.QRect(90, 450, 821, 91))
            font = QtGui.QFont()
            font.setPointSize(15)
            font.setBold(True)
            font.setWeight(75)
            self.formula_graph_1.setFont(font)
            self.formula_graph_1.setStyleSheet("background-color: rgb(85, 170, 127);")
            self.formula_graph_1.setObjectName("formula_graph_1")
            self.check_mistake_1 = QtWidgets.QCheckBox(self.graphics_main)
            self.check_mistake_1.setGeometry(QtCore.QRect(250, 300, 131, 20))
            self.check_mistake_1.setObjectName("check_mistake_1")
            self.check_zero_1 = QtWidgets.QCheckBox(self.graphics_main)
            self.check_zero_1.setGeometry(QtCore.QRect(430, 300, 131, 20))
            self.check_zero_1.setObjectName("check_zero_1")
            self.check_extremum_1 = QtWidgets.QCheckBox(self.graphics_main)
            self.check_extremum_1.setGeometry(QtCore.QRect(600, 300, 131, 20))
            self.check_extremum_1.setObjectName("check_extremum_1")
            self.label_graph_high_4 = QtWidgets.QLabel(self.graphics_main)
            self.label_graph_high_4.setGeometry(QtCore.QRect(340, 270, 331, 21))
            font = QtGui.QFont()
            font.setPointSize(10)
            font.setBold(True)
            font.setWeight(75)
            self.label_graph_high_4.setFont(font)
            self.label_graph_high_4.setObjectName("label_graph_high_4")
            self.btn_start_graph_1 = QtWidgets.QPushButton(self.graphics_main)
            self.btn_start_graph_1.setGeometry(QtCore.QRect(390, 340, 191, 51))
            font = QtGui.QFont()
            font.setPointSize(10)
            font.setBold(True)
            font.setWeight(75)
            self.btn_start_graph_1.setFont(font)
            self.btn_start_graph_1.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"backgro    und-color: rgb(170, 170, 255);")
            self.btn_start_graph_1.setObjectName("btn_start_graph_1")
            self.formula_graph_need_1 = QtWidgets.QTextEdit(self.graphics_main)
            self.formula_graph_need_1.setGeometry(QtCore.QRect(100, 40, 801, 87))
            font = QtGui.QFont()
            font.setPointSize(15)
            font.setBold(True)
            font.setWeight(75)
            self.formula_graph_need_1.setFont(font)
            self.formula_graph_need_1.setObjectName("formula_graph_need_1")
            self.point_X_1 = QtWidgets.QPlainTextEdit(self.graphics_main)
            self.point_X_1.setGeometry(QtCore.QRect(350, 160, 261, 41))
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            self.point_X_1.setFont(font)
            self.point_X_1.setObjectName("point_X_1")
            self.point_Y_1 = QtWidgets.QPlainTextEdit(self.graphics_main)
            self.point_Y_1.setGeometry(QtCore.QRect(350, 220, 261, 41))
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            self.point_Y_1.setFont(font)
            self.point_Y_1.setObjectName("point_Y_1")
            self.btn_add_graph_1 = QtWidgets.QPushButton(self.graphics_main)
            self.btn_add_graph_1.setGeometry(QtCore.QRect(200, 560, 261, 71))
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            self.btn_add_graph_1.setFont(font)
            self.btn_add_graph_1.setStyleSheet("background-color: rgb(255, 0, 0);")
            self.btn_add_graph_1.setObjectName("btn_add_graph_1")
            self.btn_new_graph_1 = QtWidgets.QPushButton(self.graphics_main)
            self.btn_new_graph_1.setGeometry(QtCore.QRect(540, 560, 261, 71))
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            self.btn_new_graph_1.setFont(font)
            self.btn_new_graph_1.setStyleSheet("background-color: rgb(85, 170, 255);")
            self.btn_new_graph_1.setObjectName("btn_new_graph_1")
            self.menu_graphics.addTab(self.graphics_main, "")
        create_graphics(self)
        self.menu.addTab(self.graphics, "")

        def create_mis(self):
            self.mistakes = QtWidgets.QWidget()
            self.mistakes.setObjectName("mistakes")
            self.label_mis_high_1 = QtWidgets.QLabel(self.mistakes)
            self.label_mis_high_1.setGeometry(QtCore.QRect(320, 10, 391, 41))
            font = QtGui.QFont()
            font.setPointSize(10)
            font.setBold(True)
            font.setWeight(75)
            self.label_mis_high_1.setFont(font)
            self.label_mis_high_1.setObjectName("label_mis_high_1")
            self.label_mis_high_2 = QtWidgets.QLabel(self.mistakes)
            self.label_mis_high_2.setGeometry(QtCore.QRect(230, 130, 521, 41))
            font = QtGui.QFont()
            font.setPointSize(10)
            font.setBold(True)
            font.setWeight(75)
            self.label_mis_high_2.setFont(font)
            self.label_mis_high_2.setObjectName("label_mis_high_2")
            self.label_mis_high_5 = QtWidgets.QLabel(self.mistakes)
            self.label_mis_high_5.setGeometry(QtCore.QRect(310, 310, 611, 41))
            font = QtGui.QFont()
            font.setPointSize(10)
            font.setBold(True)
            font.setWeight(75)
            self.label_mis_high_5.setFont(font)
            self.label_mis_high_5.setObjectName("label_mis_high_5")
            self.number_mistake = QtWidgets.QLabel(self.mistakes)
            self.number_mistake.setGeometry(QtCore.QRect(290, 530, 471, 61))
            font = QtGui.QFont()
            font.setPointSize(10)
            font.setBold(True)
            font.setWeight(75)
            self.number_mistake.setFont(font)
            self.number_mistake.setStyleSheet("background-color: rgb(255, 255, 127);")
            self.number_mistake.setObjectName("number_mistake")
            self.mistake_name_const = QtWidgets.QTextEdit(self.mistakes)
            self.mistake_name_const.setGeometry(QtCore.QRect(310, 160, 231, 41))
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            self.mistake_name_const.setFont(font)
            self.mistake_name_const.setObjectName("mistake_name_const")
            self.formula_mistake_need = QtWidgets.QTextEdit(self.mistakes)
            self.formula_mistake_need.setGeometry(QtCore.QRect(270, 50, 501, 87))
            font = QtGui.QFont()
            font.setPointSize(15)
            font.setBold(True)
            font.setWeight(75)
            self.formula_mistake_need.setFont(font)
            self.formula_mistake_need.setObjectName("formula_mistake_need")
            self.label_small_1 = QtWidgets.QLabel(self.mistakes)
            self.label_small_1.setGeometry(QtCore.QRect(190, 360, 141, 16))
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            self.label_small_1.setFont(font)
            self.label_small_1.setObjectName("label_small_1")
            self.label_small_2 = QtWidgets.QLabel(self.mistakes)
            self.label_small_2.setGeometry(QtCore.QRect(460, 360, 141, 16))
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            self.label_small_2.setFont(font)
            self.label_small_2.setObjectName("label_small_2")
            self.label_small_3 = QtWidgets.QLabel(self.mistakes)
            self.label_small_3.setGeometry(QtCore.QRect(730, 360, 161, 16))
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            self.label_small_3.setFont(font)
            self.label_small_3.setObjectName("label_small_3")
            self.horizontalLayoutWidget = QtWidgets.QWidget(self.mistakes)
            self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 380, 821, 89))
            self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
            self.verticalCorrect_mis = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
            self.verticalCorrect_mis.setContentsMargins(0, 0, 0, 0)
            self.verticalCorrect_mis.setObjectName("verticalCorrect_mis")
            self.text_mistake_const = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            self.text_mistake_const.setFont(font)
            self.text_mistake_const.setPlainText("")
            self.text_mistake_const.setObjectName("text_mistake_const")
            self.verticalCorrect_mis.addWidget(self.text_mistake_const)
            self.text_mistake_var_middle = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            self.text_mistake_var_middle.setFont(font)
            self.text_mistake_var_middle.setPlainText("")
            self.text_mistake_var_middle.setObjectName("text_mistake_var_middle")
            self.verticalCorrect_mis.addWidget(self.text_mistake_var_middle)
            self.text_mistake_var_deviation = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            self.text_mistake_var_deviation.setFont(font)
            self.text_mistake_var_deviation.setPlainText("")
            self.text_mistake_var_deviation.setObjectName("text_mistake_var_deviation")
            self.verticalCorrect_mis.addWidget(self.text_mistake_var_deviation)
            self.btn_mis_getFormula = QtWidgets.QPushButton(self.mistakes)
            self.btn_mis_getFormula.setGeometry(QtCore.QRect(620, 160, 231, 41))
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            self.btn_mis_getFormula.setFont(font)
            self.btn_mis_getFormula.setStyleSheet("background-color: rgb(255, 170, 127);")
            self.btn_mis_getFormula.setObjectName("btn_mis_getFormula")
            self.formula_mistake = QtWidgets.QLabel(self.mistakes)
            self.formula_mistake.setGeometry(QtCore.QRect(180, 210, 691, 87))
            font = QtGui.QFont()
            font.setPointSize(10)
            font.setBold(True)
            font.setWeight(75)
            self.formula_mistake.setFont(font)
            self.formula_mistake.setStyleSheet("background-color: rgb(255, 170, 0);")
            self.formula_mistake.setObjectName("formula_mistake")
            self.btn_mis_getFigure = QtWidgets.QPushButton(self.mistakes)
            self.btn_mis_getFigure.setGeometry(QtCore.QRect(400, 480, 251, 41))
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            self.btn_mis_getFigure.setFont(font)
            self.btn_mis_getFigure.setStyleSheet("background-color: rgb(255, 255, 0);")
            self.btn_mis_getFigure.setObjectName("btn_mis_getFigure")
            self.btn_mis_new = QtWidgets.QPushButton(self.mistakes)
            self.btn_mis_new.setGeometry(QtCore.QRect(392, 610, 271, 41))
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            self.btn_mis_new.setFont(font)
            self.btn_mis_new.setStyleSheet("\n"
"background-color: rgb(255, 85, 0);")
        create_mis(self)
        self.btn_mis_new.setObjectName("btn_mis_new")
        self.menu.addTab(self.mistakes, "")

        def createMenuBar(self):
            self.menuBar = QMenuBar(self)
            self.setMenuBar(self.menuBar)

            fileMenu = QMenu("&Файл", self)
            self.menuBar.addMenu(fileMenu)

            # open_file = fileMenu.addMenu("&Открыть")
            # save_file = fileMenu.addMenu("&Сохранить")

            fileMenu.addAction('Открыть', self.action_clicked)
            fileMenu.addAction('Сохранить', self.action_clicked)

        @QtCore.pyqtSlot()
        def action_clicked(self):
            action = self.sender()
            if action.text() == "Открыть":
                fname = QFileDialog.getOpenFileName(self)[0]
                try:
                    f = open(fname, 'r')
                    with f:
                        date = f.read()
                        self.text_edit.setText(date)
                    f.close()
                except FileNotFoundError:
                    print('No such file')

            elif action.text() == "Сохранить":
                fname = QFileDialog.getSaveFileName(self)[0]
                try:
                    f = open(fname, 'w')
                    text = self.text_edit.toPlainText()
                    f.write(text)
                    f.close()
                except FileNotFoundError:
                    print('No such file')

        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_2)
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.menu.setCurrentIndex(2)
        self.menu_graphics.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        # Здесь происходит занесение созданных объектов в пользовательское окно
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_ex.setText(_translate("MainWindow", "Введите полный путь к Excel файлу,\n"
"с которым вы собираетесь работать\n"
"(из этого файла будут считываться данные\n"
"указанные через индексы)"))
        self.btn_ex.setText(_translate("MainWindow", "Работать с этим файлом!"))
        self.menu.setTabText(self.menu.indexOf(self.ecxel_fail), _translate("MainWindow", "Выбор excel файла"))
        self.label_graph_high_1.setText(_translate("MainWindow", "введите формулу для графика:"))
        self.label_graphics_high_3.setText(_translate("MainWindow", "введите данные(точки графика):"))
        self.label_graph_X_1.setText(_translate("MainWindow", "x"))
        self.label_graphics_Y_1.setText(_translate("MainWindow", "y"))
        self.label_label_high_5.setText(_translate("MainWindow", "здесь вы получите формулу приближенного графика"))
        self.formula_graph_1.setText(_translate("MainWindow", "формула для вашего графика:"))
        self.check_mistake_1.setText(_translate("MainWindow", "Хочу погрешность"))
        self.check_zero_1.setText(_translate("MainWindow", "Хочу нули ф-ии"))
        self.check_extremum_1.setText(_translate("MainWindow", "хочу экстремумы"))
        self.label_graph_high_4.setText(_translate("MainWindow", "добавьте галочки, если нужно"))
        self.btn_start_graph_1.setText(_translate("MainWindow", "Получить график!"))
        self.btn_add_graph_1.setText(_translate("MainWindow", "хочу добавить график\n"
"в те же координатные оси"))
        self.btn_new_graph_1.setText(_translate("MainWindow", "Хочу создавать новый график.\n"
"Соглашаюсь удалить\n"
"предыдущие мои графики"))
        self.menu_graphics.setTabText(self.menu_graphics.indexOf(self.graphics_main), _translate("MainWindow", "главный график"))
        self.menu.setTabText(self.menu.indexOf(self.graphics), _translate("MainWindow", "графики"))
        self.label_mis_high_1.setText(_translate("MainWindow", "введите формулу для величины, \n"
"погрешность которой вы хотите посчитать"))
        self.label_mis_high_2.setText(_translate("MainWindow", "укажите, какие буквы являются константой"))
        self.label_mis_high_5.setText(_translate("MainWindow", "если хотите получить числовое значение,\n"
"введите числовые значения переменных и констант"))
        self.number_mistake.setText(_translate("MainWindow", "Здесь вы получите числовое значение:"))
        self.label_small_1.setText(_translate("MainWindow", "значение констант"))
        self.label_small_2.setText(_translate("MainWindow", "среднее переменной"))
        self.label_small_3.setText(_translate("MainWindow", "среднекв. отклонение"))
        self.btn_mis_getFormula.setText(_translate("MainWindow", "Получить формулу погрешности"))
        self.formula_mistake.setText(_translate("MainWindow", "Здесь вы получите формулу погрешности:"))
        self.btn_mis_getFigure.setText(_translate("MainWindow", "Получить числовое значение"))
        self.btn_mis_new.setText(_translate("MainWindow", "Обновить окно!"))
        self.menu.setTabText(self.menu.indexOf(self.mistakes), _translate("MainWindow", "Погрешности"))
        self.menu_2.setTitle(_translate("MainWindow", "Справка"))
        self.action_2.setText(_translate("MainWindow", "О программе"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
